### ISSUE TITLE
Just started the project an 404 js

### ISSUE THREAD

**Issue by FDiskas** [stealjs/quick-start#5]
```
[Sun Jan 08 2017 23:04:20 GMT+0200 (FLE Standard Time)] "GET /dist/bundles/index.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
[Sun Jan 08 2017 23:04:20 GMT+0200 (FLE Standard Time)] "GET /dist/bundles/index.js" Error (404): "Not found"
```
the file is created in a different location
```dist/bundles/stealjs/index.js```

**Comment by chasenlehara** [comment]
Thanks for reporting the issue. I can’t seem to reproduce it though. We recently updated some of the dependencies, so perhaps this was fixed by that.

If you’re still able to reproduce this issue, please include which version of Node and npm you’re using, as well as how you’re serving the files. Thank you!
